### ISSUE TITLE
Awesome job man!

### ISSUE THREAD

**Issue by abusiv0** [NiroDeveloper/Valorant-Color-Cheat#1]
You have done an excellent job, congratulations!
The detection of characters is very good, unfortunately it stopped working in the update of May 12

**Comment by Perustaja** [comment]
Is it not aiming or clicking? I am working on something similar in Rust for speed and am going to test it tonight. Hoping their anti-cheat is not somehow preventing certain windows api calls while the game is open or active.

**Comment by abusiv0** [comment]
not aiming any more
